
DROP TABLE IF EXISTS `_SessionSqlStore`;
DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `Oauth`;
DROP TABLE IF EXISTS `Category`
DROP TABLE IF EXISTS `Area`
DROP TABLE IF EXISTS `UserArea`
DROP TABLE IF EXISTS `Product`
DROP TABLE IF EXISTS `Media`
DROP TABLE IF EXISTS `ProductCategory`
DROP TABLE IF EXISTS `ProductMedia`